apiVersion: apps/v1
kind: Deployment
metadata:
  name: charters
spec:
  selector:
    matchLabels:
      app: chartersms
  replicas: 1
  template:
    metadata:
      labels:
        app: chartersms
    spec:
      containers:
        - name: chartersms
          image: us.icr.io/tcrowley-vpc-ns/charters
          imagePullPolicy: Always
          ports:
          - containerPort: 3001
          env:
          - name: DB_HOST
            value: '1758ec87-47c1-4bea-b397-75adeaa26611.budepemd0im5pmu4u60g.databases.appdomain.cloud'
          - name: DB_NAME
            value: 'ibmclouddb'
          - name: DB_PORT
            value: '32390'
          - name: DB_USE_SSL
            value: '<no value>'
          - name: MY_PORT
            value: '3001'
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: databasecredentials
                key: db_password
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: databasecredentials
                key: db_username
---
apiVersion: v1
kind: Service
metadata:
  name: chartersms-service
  namespace: default
  labels:
    app: charters
spec:
  type: NodePort
  selector:
    app: chartersms
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30163
